"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#87a987)\
[  ](bg:#87a987 fg:#181616)\
[](bg:#c4b28a fg:#87a987)\
$directory\
[](fg:#c4b28a bg:#252535)\
$git_branch\
$git_status\
[](fg:#252535 bg:#1f1f28)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1f1f28 bg:#181616)\
$time\
[ ](fg:#181616)\
\n$character"""

[directory]
style = "fg:#181616 bg:#c4b28a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#252535"
format = '[[ $symbol $branch ](fg:#87a987 bg:#252535)]($style)'

[git_status]
style = "bg:#252535"
format = '[[($all_status$ahead_behind )](fg:#c4b28a bg:#252535)]($style)'

[nodejs]
symbol = ""
style = "bg:#1f1f28"
format = '[[ $symbol ($version) ](fg:#87a987 bg:#1f1f28)]($style)'

[rust]
symbol = ""
style = "bg:#1f1f28"
format = '[[ $symbol ($version) ](fg:#c4746e bg:#1f1f28)]($style)'

[golang]
symbol = ""
style = "bg:#1f1f28"
format = '[[ $symbol ($version) ](fg:#8ba4b0 bg:#1f1f28)]($style)'

[php]
symbol = ""
style = "bg:#1f1f28"
format = '[[ $symbol ($version) ](fg:#a292a3 bg:#1f1f28)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#181616"
format = '[[  $time ](fg:#c5c9c5 bg:#181616)]($style)'